# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sdns < Formula
  desc "A high-performance, recursive DNS resolver server with DNSSEC support, focused on preserving privacy"
  homepage "https://sdns.dev"
  version "1.6.7"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/semihalev/sdns/releases/download/v1.6.7/sdns-1.6.7_darwin_amd64.tar.gz"
      sha256 "67075f2d73ff455793adbe880a1a43e2bba5a214e246c7e75bd60fadde1f3ab9"

      define_method(:install) do
        bin.install "sdns"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/semihalev/sdns/releases/download/v1.6.7/sdns-1.6.7_darwin_arm64.tar.gz"
      sha256 "d54454c4e6befe3103db8776ffcc230b817d1de34decab890ddf9847fb30ce00"

      define_method(:install) do
        bin.install "sdns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/semihalev/sdns/releases/download/v1.6.7/sdns-1.6.7_linux_amd64.tar.gz"
      sha256 "8812c27f87313ee851501dd85f833b9f2b05647e66117c65664ff7b217436342"
      define_method(:install) do
        bin.install "sdns"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/semihalev/sdns/releases/download/v1.6.7/sdns-1.6.7_linux_armv6.tar.gz"
      sha256 "6d5bd1b162e678f10b250dbcdbd30219531cc8964a52b779d30d5898771c825e"
      define_method(:install) do
        bin.install "sdns"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/semihalev/sdns/releases/download/v1.6.7/sdns-1.6.7_linux_arm64.tar.gz"
      sha256 "3146e48e879ed3de695dcdaf05f6965eef163391bfdf94170b8e952e8b96fb7c"
      define_method(:install) do
        bin.install "sdns"
      end
    end
  end

  service do
    run [opt_bin/"sdns", "-config", etc/"sdns.conf"]
    keep_alive true
    require_root true
    error_log_path var/"log/sdns.log"
    log_path var/"log/sdns.log"
    working_dir opt_prefix
  end

  test do
    fork do
      exec bin/"sdns", "-config", testpath/"sdns.conf"
    end
    sleep(2)
    assert_predicate testpath/"sdns.conf", :exist?
  end
end
